---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://sperezbu.github.io/unixway"
title: "Unix High Performance Team"
canonifyurls: true
...
